/*
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
*/

#include<iostream>
#include<string>
using namespace std;

void sortString(string str, int length);

int main(){
  string str1;
  string str2;

  // Ask user for input
  cout << "Enter in the first string:" << endl;
  cin>>str1;
  cout<<"Enter in the second string(one more letter than the first): "<<endl;
  cin>>str2;

  // Sort string in alphabetical order
  int length1=str1.length();
  int length2=str2.length();
  sortString(str1,length1);
  sortString(str2,length2);

  // Check which one is different
  for(int i=0;i<str2.length();i++){
      if(str1[i]!=str2[i]){
        cout<<"The letter \""<<str2[i]<<"\" is the letter that was added"<<endl;
        break;
      }
  }
  return 0;
}

// Use Bubble Sort to sort string in alphabetical order
void sortString(string str, int length){
  for(int i=length-1;i>0;i--){
    for(int j=0;j<i;j++){
      if(str[j]<str[j+1]){
        int temp=str[j+1];
        str[j+1]=str[j];
        str[j]=temp;
      }
    }
  }
}
