/*
 * FASTER RUNTIME
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
*/

#include<iostream>
#include<string>
using namespace std;

int main(){
  string str1;
  string str2;
  int ascii[127];

  // Put all the values to 0
  for (int i = 0; i < 127; i++) {
    ascii[i] = 0;
  }

  // Ask user for input
  cout << "Enter in the first string:" << endl;
  cin>>str1;
  cout<<"Enter in the second string(one more letter than the first): "<<endl;
  cin>>str2;

  // Increment the letters used in each string
  for(int i=0;i<str1.length();i++){
    ascii[(int)str1[i]]++;
  }
  for(int i=0;i<str2.length();i++){
    ascii[(int)str2[i]]++;
  }

  // Find the letter that is only incremented once
  for(int i=0; i<127;i++){
    if(ascii[i]==1){
      cout<<"The letter \""<< (char) i <<"\" is the letter that was added"<<endl;
    }
  }

  return 0;
}
